export const QUICK_VIEW_COPY = {
  mrp: "",
  inclusiveText: "Impuestos incluidos",
  off: "dto.",
  reviews: "reseñas",
  addToCart: "Agregar al carrito",
  buyNow: "Comprar ahora",
  outOfStock: "Agotado",
  addToWishlist: "Agregar a favoritos",
  whatsappInquiry: "Consultar por WhatsApp",
  deliveryDetails: "Detalles de envío",
  estimatedDelivery: "Entrega estimada en 1-2 días hábiles",
  returnPolicy: "Devoluciones fáciles dentro de 3 días",
  sale: "Oferta",
} as const;
