export const CART_COPY = {
  pageTitle: "Carrito",
  pageDescription: "Revisa los productos que agregaste antes de finalizar tu compra.",
  breadcrumbHome: "Inicio",
  breadcrumbCurrent: "Carrito",
  image: "Imagen",
  product: "Producto",
  price: "Precio",
  quantity: "Cantidad",
  total: "Total",
  action: "Acción",
  totalPrice: "Total",
  continueShopping: "Seguir comprando",
  checkout: "Checkout",
  emptyTitle: "Tu carrito está vacío",
  emptyDescription: "Aún no has agregado productos. Explora nuestras colecciones y encuentra lo que buscas.",
  exploreCollections: "Explorar colecciones",
  removeItem: "Eliminar producto",
  decreaseQuantity: "Disminuir cantidad",
  increaseQuantity: "Aumentar cantidad",
} as const;
