export const CART_COPY = {
  pageTitle: "Carrito",
  pageDescription: "Revisa los productos que agregaste antes de finalizar tu compra.",
  breadcrumbHome: "Inicio",
  breadcrumbCurrent: "Carrito",
  image: "Imagen",
  product: "Producto",
  price: "Precio",
  quantity: "Cantidad",
  total: "Total",
  action: "Acción",
  totalPrice: "Total",
  continueShopping: "Seguir comprando",
  continueShoppingShort: "Seguir",
  viewCart: "Ver carrito",
  viewCartShort: "Carrito",
  whatsappCart: "Comprar carrito por WhatsApp",
  whatsappPage: "Comprar por WhatsApp",
  whatsappShort: "WhatsApp",
  checkout: "Checkout",
  checkoutShort: "Finalizar",
  emptyTitle: "Tu carrito está vacío",
  emptyDescription: "Aún no has agregado productos. Explora nuestras colecciones y encuentra lo que buscas.",
  exploreCollections: "Explorar colecciones",
  removeItem: "Eliminar producto",
  decreaseQuantity: "Disminuir cantidad",
  increaseQuantity: "Aumentar cantidad",
  editVariation: "Editar variación",
  editVariationTitle: "Editar variación",
  editVariationCurrent: "En tu carrito",
  updateItem: "Actualizar producto",
  updateItemShort: "Guardar cambios",
  loadingProduct: "Cargando producto…",
  productLoadError: "No se pudo cargar el producto. Intenta de nuevo.",
} as const;
